name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      # Use GitHub's own checkout action which is always allowed
      - name: Checkout code
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git .
          git checkout ${{ github.sha }}
          
      # Setup Docker Buildx manually
      - name: Set up Docker Buildx
        run: |
          # Enable experimental features in Docker
          echo '{"experimental": true}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker || true
          
          # Install qemu for multi-platform builds
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          
          # Setup buildx
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          
      # Login to GitHub Container Registry
      - name: Login to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      # Build and push the Docker image
      - name: Build and push Docker image
        run: |
          # Lower case the repo name (GitHub packages require lowercase)
          IMAGE_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          
          # Build multi-architecture image
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "ghcr.io/$IMAGE_NAME:latest" \
            --push \
            .